version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: penedgeAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: penedge1234
    volumes:
      - ./data:/data/db
  nginx:
    container_name: nginx
    image: nginx
    restart: always
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 80:80
    links:
      - mongo
      - nginx
    volumes:
      - ./app:/AppData