version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 80:80
    volumes:
      - .:/admin/static/admin/content/
      - .:/admin/static/admin/profile_image/
      - ./admin/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    links:
      - mongo
      - app